const shopItemsData = [
  {
    id: "1",
    name: "Giraffaa",
    price: 99.99,
    img: "./img/img--index/products/product-giraffa.jpeg",
    desc: "Smart and playful, Giraffa’s endearing personality and versatile design are at home anywhere: on your desk, atop a nightstand, or tucked into a cozy reading nook. A 360° rotating shade combined with an angled post provides multiple lighting possibilities, allowing this petite lamp to cast both direct and ambient light. ",
    category: "table",
  },
  {
    id: "2",
    name: "Solis",
    price: 79.99,
    img: "./img/img--index/products/product-Solis.jpeg",
    desc: "In creating Solis, designer Carmine Deganello set out to engage with light in its archetypal form: the sun’s rays.",
    category: "floor",
  },
  {
    id: "3",
    name: "Corner Office",
    price: 192.99,
    img: "./img/img--index/products/product-Corner.jpeg",
    desc: "Today, everyplace is a workplace. Due to the constantly changing landscape of work, the new open workplace can be inconvenient, uninviting and distracting.",
    category: "table",
  },
  {
    id: "4",
    name: "Cielo",
    price: 89.99,
    img: "./img/img--index/products/product-cielo.jpeg",
    desc: "Through its minimal form and glare-free, flat panel LED technology, Cielo enables light to act as its expressive element and defining feature.",
    category: "ceiling",
  },
  {
    id: "5",
    name: "Uma Mini",
    price: 155.99,
    img: "./img/img--index/products/product-uma.jpg",
    desc: "Introducing UMA Mini, the newest addition to the UMA family, now more portable than ever to travel with you anywhere you go.",
    category: "table",
  },
  {
    id: "6",
    name: "Contour",
    price: 245.99,
    img: "./img/img--index/products/product-contour.jpg",
    desc: "Contour’s revealing and elegant open framed architecture captures warm LED illumination within a remarkably slender extruded aluminum structure.",
    category: "floor",
  },
  {
    id: "7",
    name: "Circa",
    price: 398.99,
    img: "./img/img--index/products/product-circa.jpg",
    desc: "In designing Circa, the Pablo Studio designers wanted to create a product that was revolutionary yet familiar.",
    category: "ceiling",
  },
  {
    id: "8",
    name: "Bola Sphere",
    price: 789.99,
    img: "./img/img--index/products/product-bola-sphere.jpg",
    desc: "The Bola Sphere Pendant is the basic foundation for the Bola Collection, featuring an elemental interplay between post and sphere.",
    category: "ceiling",
  },
  {
    id: "9",
    name: "Bola Disc",
    price: 1125.99,
    img: "./img/img--index/products/product-bola-disc.jpg",
    desc: "Bola Disc is a uniquely expressive LED Pendant system featuring a distinctive range of chromated disc reflectors that give the illusion of weightlessness by mirroring its surroundings.",
    category: "ceiling",
  },
  {
    id: "10",
    name: "Belmont",
    price: 717.99,
    img: "./img/img--index/products/product-belmont.jpg",
    desc: "The Belmont Collection was a collaborative creation with designer Brad Ascalon re-envisioning the traditional fabric shade lamp but with the warmth and preciousness of hand crafted furniture.",
    category: "ceiling",
  },
  {
    id: "11",
    name: "Bel Occhio",
    price: 515.99,
    img: "./img/img--index/products/product-bel-occhio.jpg",
    desc: "Bel Occhio is a study in weightlessness and transparency,” notes designer Pablo Pardo on his inspiration for this luminaire.",
    category: "ceiling",
  },
  {
    id: "12",
    name: "Bola Halo",
    price: 435.99,
    img: "./img/img--index/products/product-bola-halo.jpg",
    desc: "Taking its inspiration from pendant jewelry, Bola Halo is a uniquely expressive pendant light featuring a chromated ring that balances delicately over its elegant opal glass shade while allowing its surroundings to shine through.",
    category: "ceiling",
  },
];

export default shopItemsData;
